Repository lemokami/startupsofkerala, pull requests merged in 2022-10, with the labels that each got.

#3 Added Katha
  data/katha.mdx
  public/logos/katha-logo.png
Labels: hacktoberfest

#6 Added 2 startups
  data/aion.mdx
  data/spotix.mdx
  package.json
  public/logos/aion-logo.jpeg
  public/logos/spotix.jpeg
  src/assets/firebase-logo.png
  src/assets/nodejs-logo.png
  src/assets/pwa-logo.png
  src/components/Card.jsx
  src/constants/logoMap.json
  tailwind.config.cjs
  yarn.lock
Labels: hacktoberfest, hactoberfest-accepted

#4 Added startup
  data/surveysparrow.mdx
  public/logos/SurveySparrow.png
Labels: hacktoberfest

#14 Added Entri App mdx file and logo
  data/entri.mdx
  public/logos/entri.png
Labels: hacktoberfest, hacktoberfest-accepted

#17 added new startup info
  data/sastra.mdx
  public/logos/sastra.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#21 Added paysack
  data/Paysack.mdx
  public/logos/paysack.png
Labels: hacktoberfest, hacktoberfest-accepted
